# Generated by Django 5.0.2 on 2026-02-04 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Unidades en Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está a la venta?')),
                ('product_type', models.CharField(choices=[('SINGLE', 'Producto Individual'), ('COMBO', 'Combo / Paquete')], default='SINGLE', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='URL de la imagen del producto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('parent_combo', models.ForeignKey(limit_choices_to={'product_type': 'COMBO'}, on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='products.product')),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'SINGLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='included_in_combos', to='products.product')),
            ],
            options={
                'verbose_name': 'Ítem de Combo',
                'verbose_name_plural': 'Contenido de Combos',
            },
        ),
    ]
