# Generated by Django 5.0.2 on 2026-02-04 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Lugar')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Capacidad Máxima')),
                ('layout', models.JSONField(blank=True, default=dict, verbose_name='Diseño de Sillas (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teatro / Venue',
                'verbose_name_plural': 'Teatros / Venues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShowFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Show')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Sinopsis')),
                ('poster_url', models.URLField(blank=True, null=True, verbose_name='URL del Poster')),
                ('date_time', models.DateTimeField(db_index=True, verbose_name='Fecha y Hora')),
                ('active', models.BooleanField(default=True, verbose_name='¿A la venta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='functions', to='events.venue', verbose_name='Lugar')),
            ],
            options={
                'verbose_name': 'Función / Evento',
                'verbose_name_plural': 'Funciones / Eventos',
                'ordering': ['date_time'],
            },
        ),
    ]
