# Generated by Django 5.0.2 on 2026-02-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showfunction',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='showfunction',
            name='poster',
            field=models.ImageField(blank=True, help_text='Formatos recomendados: JPG, PNG. Resolución óptima: 800x1200px.', null=True, upload_to='events/posters/', verbose_name='Poster del Evento'),
        ),
        migrations.AlterField(
            model_name='showfunction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Sinopsis'),
        ),
    ]
