# Generated by Django 5.0.2 on 2026-02-05 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_showfunction_poster_url_showfunction_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ej: VIP, General, Platinum, Early Bird', max_length=100, verbose_name='Nombre de la Categoría')),
                ('zone_code', models.CharField(help_text="Debe coincidir con la etiqueta 'zone' o 'category' en el diseño de sillas. Ej: 'vip', 'platea_a'.", max_length=50, verbose_name='Código de Zona en Mapa')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de Venta')),
                ('color', models.CharField(default='#3388ff', help_text='Código Hexadecimal para pintar las sillas. Ej: #FFD700 (Dorado)', max_length=7, verbose_name='Color en el Mapa')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Solo si la zona NO tiene sillas numeradas (Admisión General).', verbose_name='Capacidad (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.showfunction', verbose_name='Función')),
            ],
            options={
                'verbose_name': 'Tipo de Boleta / Precio',
                'verbose_name_plural': 'Lista de Precios',
                'unique_together': {('function', 'zone_code')},
            },
        ),
    ]
