# Generated by Django 5.0.2 on 2026-02-04 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('APPROVED', 'Aprobada (Pagada)'), ('REJECTED', 'Rechazada/Fallida'), ('CANCELLED', 'Cancelada por Usuario')], db_index=True, default='PENDING', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total a Pagar')),
                ('wompi_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('wompi_reference', models.CharField(blank=True, help_text='Referencia única para pasarela', max_length=100, unique=True)),
                ('siigo_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
            ],
            options={
                'verbose_name': 'Item de Producto',
                'verbose_name_plural': 'Items de Productos',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_label', models.CharField(max_length=50, verbose_name='Ubicación')),
                ('seat_category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Pagado')),
                ('qr_token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('state', models.CharField(choices=[('ISSUED', 'Emitido / Valido'), ('INSIDE', 'Adentro del Evento'), ('TEMP_EXIT', 'Salida Temporal'), ('CONSUMED', 'Finalizado / Quemado'), ('CANCELLED', 'Anulado por Fraude')], db_index=True, default='ISSUED', max_length=20)),
                ('last_entry_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Entrada')),
                ('last_exit_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Salida')),
            ],
            options={
                'verbose_name': 'Ticket / Boleta',
                'verbose_name_plural': 'Tickets / Boletas',
            },
        ),
    ]
