# Generated by Django 5.0.2 on 2026-06-10 18:59

import apps.orders.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tickettype'),
        ('orders', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gate_id', models.CharField(max_length=50)),
                ('scanner_agent_id', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('ENTRY', 'Entrada Autorizada'), ('EXIT', 'Salida Temporal'), ('DENIED', 'Acceso Denegado')], max_length=20)),
                ('state_at_scan', models.CharField(max_length=20)),
                ('reason', models.CharField(default='OK', max_length=255)),
                ('integrity_hash', models.CharField(editable=False, max_length=64)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_entry_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_exit_at',
        ),
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Verificación cruzada (Cross-Check)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='COP', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cargos por servicio (Ticketera)', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Log crudo e inmutable del Webhook'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Impuestos calculados', max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='crypto_signature',
            field=models.CharField(default='', editable=False, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='key_version',
            field=models.PositiveIntegerField(default=1, editable=False, help_text='Permite rotación de llaves de seguridad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='siigo_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PROCESSING', 'Procesando en Pasarela'), ('APPROVED', 'Aprobada (Pagada)'), ('REJECTED', 'Rechazada/Fallida'), ('CANCELLED', 'Cancelada'), ('REFUNDED', 'Reembolsada (Devolución)')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='wompi_reference',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_order_reference, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wompi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sold_tickets', to='events.showfunction'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_token',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_secure_token, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat_label',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('ISSUED', 'Emitido / Válido'), ('INSIDE', 'Adentro del Recinto'), ('TEMP_EXIT', 'Salida Temporal'), ('CONSUMED', 'Finalizado / Quemado'), ('BLOCKED', 'Bloqueado por Fraude'), ('REFUNDED', 'Devuelto al inventario')], db_index=True, default='ISSUED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_token', 'state'], name='orders_tick_qr_toke_ebd184_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['function', 'state'], name='orders_tick_functio_68e46d_idx'),
        ),
        migrations.AddField(
            model_name='ticketscan',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='scans', to='orders.ticket'),
        ),
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['ticket', 'timestamp'], name='orders_tick_ticket__28a97d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscan',
            index=models.Index(fields=['gate_id', 'timestamp'], name='orders_tick_gate_id_024f41_idx'),
        ),
    ]
