# Generated by Django 5.0.2 on 2026-06-19 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ticketscan_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketscan',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
