# Generated by Django 5.0.2 on 2026-06-25 15:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tickettype'),
        ('orders', '0004_alter_ticketscan_timestamp'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='orders_tick_functio_68e46d_idx',
        ),
        migrations.AddField(
            model_name='ticketscan',
            name='previous_hash',
            field=models.CharField(default='GENESIS_BLOCK', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Pago'), ('PROCESSING', 'Procesando en Pasarela'), ('APPROVED', 'Aprobada (Pagada)'), ('REJECTED', 'Rechazada/Fallida'), ('CANCELLED', 'Cancelada (Timeout/Abandonada)'), ('REFUNDED', 'Reembolsada Totalmente')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='key_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('RESERVED', 'Reservado (En Proceso de Pago)'), ('VALID', 'Válido / Activo'), ('INSIDE', 'Adentro del Recinto'), ('TEMP_EXIT', 'Salida Temporal'), ('CONSUMED', 'Consumido / Finalizado'), ('VOIDED', 'Anulado (Pago Fallido o Expirado)'), ('BLOCKED', 'Bloqueado por Fraude'), ('REFUNDED', 'Reembolsado')], db_index=True, default='RESERVED', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['function', 'seat_label', 'state'], name='orders_tick_functio_00c8d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_amount__gte', Decimal('0.00'))), name='order_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid__lte', models.F('total_amount'))), name='order_amount_paid_not_exceed_total'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('price_at_purchase__gte', Decimal('0.00')), ('discount_applied__gte', Decimal('0.00'))), name='item_prices_positive'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(check=models.Q(('price_at_purchase__gte', Decimal('0.00'))), name='ticket_price_positive'),
        ),
    ]
