# Generated by Django 5.0.2 on 2026-06-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_ticket_orders_tick_functio_68e46d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PENDING_GENERATION', 'Generando Activos Criptográficos'), ('DELIVERED', 'Entregado de Forma Segura'), ('FAILED', 'Despacho Fallido')], db_index=True, default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tickets_dispatched',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
