# Generated by Django 5.0.2 on 2026-06-27 15:21

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_status_order_gateway_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_token',
            field=models.CharField(db_index=True, default=apps.orders.models.generate_secure_token, editable=False, max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('RESERVED', 'Reservado'), ('VALID', 'Válido / Activo'), ('INSIDE', 'Adentro del Recinto'), ('TEMP_EXIT', 'Salida Temporal'), ('CONSUMED', 'Consumido / Finalizado'), ('VOIDED', 'Anulado'), ('BLOCKED', 'Bloqueado por Fraude'), ('REFUNDED', 'Reembolsado')], db_index=True, default='RESERVED', max_length=20),
        ),
    ]
