# Generated by Django 5.0.2 on 2026-06-27 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_ticket_qr_token_alter_ticket_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommunicationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(choices=[('SENT', 'Enviado Correctamente'), ('FAILED', 'Fallo de Despacho')], db_index=True, max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminPaymentLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(default='MercadoPago', max_length=50)),
                ('gateway_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('raw_payload', models.JSONField(help_text='Copia binaria/JSON exacta del Webhook')),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_price_positive',
        ),
        migrations.AddField(
            model_name='admincommunicationlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='admincommunicationlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ticket'),
        ),
        migrations.AddField(
            model_name='adminpaymentledger',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ledgers', to='orders.order'),
        ),
    ]
